<%@ page trimDirectiveWhitespaces="true" pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" session="false"%>
<!DOCTYPE html>
<!--
                            .L
                        lO@@@@.
                     .kBGGZ8@R
                    :GhvuFSS@.
     iuZGGdZSkL.    @kYvltCZ@
    L@@RGSkuct8RC  LGUv7Tt0S@L
     .D@8OCuYYlUE0 ltL;LYtyZ@.
       L@ZEPyv7iLLd@iivTUct0dC    Generated by IUEditor (V1.2.0.3)
        c@O0hFUl7rc@YuvLrvckO@Z   http://www.iueditor.org
         ZRZCuUvLLt  rhYlvTySDW
          BGPylLLUv   ,E0CCkSDW
         ,@dEFYYU0:     SRGZG@R
          S@SkC0hd       v@@@@
           G@8dODO         .
            G@@@@.
             .;,
 -->
<HTML >
  <head>  
    <meta charset="utf-8">    
    <title>크린바스켓</title>
    <meta property="og:title" content="크린바스켓" />
    <meta name="twitter:title" content="크린바스켓">
    <meta itemprop="name" content="크린바스켓">
    <link rel="icon" type="image/x-icon" href="./resources/css/pages/project/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" type="text/css" href="./resources/common/css/reset.css">
    <link rel="stylesheet" type="text/css" href="./resources/common/css/iubase.css">
    <link rel="stylesheet" type="text/css" href="./resources/common/css/iu.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/pages/index.css">
    <script>
      variableStorage = {};
      variableStorage['mobile_menu'] = {'initial':0, 'maximum':1};
    </script>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//cdn.jsdelivr.net/velocity/1.2.2/velocity.min.js"></script>
    <script src="//cdn.jsdelivr.net/velocity/1.2.2/velocity.ui.min.js"></script>
    <script type="text/javascript" src="./resources/common/plugin/jquery.event.swipe.js"></script>
    <script type="text/javascript" src="./resources/common/plugin/jquery.event.move.js"></script>
    <script type="text/javascript" src="./resources/common/plugin/jquery.scrollto.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iuframe.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iuevent.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iuboxes.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iucarousel.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iugooglemap.js"></script>
    <script type="text/javascript" src="./resources/common/iujs/iu.js"></script>
    <!--[if lt IE 9]>
      <script type="text/javascript" src="./resources/common/ie/json2.js"></script>  
      <script type="text/javascript" src="./resources/common/ie/jquery.backgroundSize.js"></script>  
      <script type="text/javascript" src="./resources/common/ie/respond.min.js"></script>  
      <script>alert("IE9 이전 버전에서는 지원되지 않습니다. 브라우저를 업데이트해주세요.");</script>  
    <![endif]-->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:300,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/earlyaccess/nanumgothic.css' rel='stylesheet' type='text/css'>
  </head>  
  <body>  
    <div class="index IUPage IUSheet IUBox">
      <div class="Header IUHeader IUBox">
        <div class="CenterBox_7 IUCenterBox IUBox">
          <div class="Text_85 IUText IUBox" scrollLink="1">
            <a class='_IULink' href="/index.html#Section_70">  
              <p>3-STEPS</p>    
            </a>  
          </div>
          <div class="Text_19 IUText IUBox" scrollLink="1">
            <a class='_IULink' href="/index.html#Section_79">  
              <p>소개</p>    
            </a>  
          </div>
          <div class="Text_21 IUText IUBox" scrollLink="1">
            <a class='_IULink' href="/index.html#Section_81">  
              <p>서비스 지역</p>    
            </a>  
          </div>
          <div class="Text_20 IUText IUBox" scrollLink="1">
            <a class='_IULink' href="/index.html#Section_27">  
              <p>가격</p>    
            </a>  
          </div>
          <div class="Text_22 IUText IUBox">
            <p>자주하는 질문</p>  
          </div>
          <img class="S_Image IUBox" src="./resources/css/pages/project/logo_wordtype.png">
          <div class="Image IUBox IUEventClickTrigger" VariableTriggerVariable="mobile_menu">
          </div>
          <div class="Box_173 IUBox IUJQueryShowEventReceiver" JQueryShowCondition="mobile_menu==1" JQueryShowAnimation="transition.slideDownIn">
            <div class="Cell_186 IUText IUBox" scrollLink="1">
              <a class='_IULink' href="/index.html#Section_70">  
                <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0><strong>3-STEPS</strong></p>    
              </a>  
            </div>
            <div class="Cell_187 IUText IUBox" scrollLink="1">
              <a class='_IULink' href="/index.html#Section_79">  
                <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>소개</p>    
              </a>  
            </div>
            <div class="Cell_188 IUText IUBox" scrollLink="1">
              <a class='_IULink' href="/index.html#Section_81">  
                <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>서비스 지역</p>    
              </a>  
            </div>
            <div class="Cell_189 IUText IUBox" scrollLink="1">
              <a class='_IULink' href="/index.html#Section_27">  
                <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>가격</p>    
              </a>  
            </div>
            <div class="Cell_190 IUText IUBox">
              <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>자주하는 질문</p>  
            </div>
          </div>
        </div>
      </div>
      <div class="PageContent IUPageContent IUBox">
        <div class="Section IUSection IUBox">
          <div class="CenterBox_16 IUCenterBox IUBox">
            <img class="S_Image_81 IUBox" src="./resources/css/pages/project/img_logo.png">
            <div class="Text_77 IUText IUBox">
              <p>크린바스켓</p>  
            </div>
            <div class="Text_42 IUText IUBox">
              <p>터치, 터치, 끝!&nbsp;번거로운 세탁 고민은 이제 잊으세요</p>  
            </div>
            <img class="S_Image_82 IUBox" src="./resources/css/pages/project/main_cleanbasketservice.png">
            <a class='_IULink' href="https://play.google.com/store/apps/details?id=com.bridge4biz.laundry" target="_blank">
              <img class="S_Image_83 IUBox" src="./resources/css/pages/project/img_google_2.png">  
            </a>
            <a class='_IULink' href="https://itunes.apple.com/kr/app/keulinbaseukes/id933165319?mt=8" target="_blank">
              <img class="S_Image_84 IUBox" src="./resources/css/pages/project/img_apple.png">  
            </a>
          </div>
        </div>
        <div id="Section_70" class="Section_70 IUSection IUBox">
          <div class="CenterBox_82 IUCenterBox IUBox">
            <div class="Box_82 IUBox">
              <div class="Box_74 IUBox">
              </div>
              <div class="Text_81 IUText IUBox">
                <p>1- STEP</p>  
              </div>
              <div class="Text_87 IUText IUBox">
                <p>설정된 시간에</p>
              <p>배달해드립니다</p>  
              </div>
              <div class="Text_82 IUText IUBox">
                <p>2-STEP</p>  
              </div>
              <div class="Box_76 IUBox">
              </div>
              <div class="Text_83 IUText IUBox">
                <p>3-STEP</p>  
              </div>
              <div class="Text_88 IUText IUBox">
                <p>세탁물 수거 후</p>
              <p>깨끗하게 세탁해드립니다</p>  
              </div>
              <img class="S_Image_80 IUBox" src="./resources/css/pages/project/ic_3steps_1.png">
              <div class="Text_84 IUText IUBox">
                <p>세탁 수거 배달 시간 설정하세요</p>
              <p>(앱/웹/전화)</p>  
              </div>
            </div>
            <div class="Text_67 IUText IUBox">
              <p>3-STEPS</p>  
            </div>
          </div>
        </div>
        <div id="Section_79" class="Section_79 IUSection IUBox">
          <div class="CenterBox_79 IUCenterBox IUBox">
            <div class="CenterBox_70 IUCenterBox IUBox">
            </div>
            <div class="Box_36 IUBox">
              <div class="Box IUBox">
                <img class="S_Image_28 IUBox" src="./resources/css/pages/project/ic_service_introduce_01mobile.png">
              </div>
              <div class="Box_31 IUBox">
                <img class="S_Image_31 IUBox" src="./resources/css/pages/project/ic_service_introduce_02cleaning.png">
              </div>
              <div class="Box_33 IUBox">
                <img class="S_Image_33 IUBox" src="./resources/css/pages/project/ic_service_introduce_03price.png">
              </div>
              <div class="Box_35 IUBox">
                <img class="S_Image_35 IUBox" src="./resources/css/pages/project/ic_service_introduce_04time.png">
              </div>
              <div class="Text IUText IUBox">
                <p><strong>편리합니다</strong></p>  
              </div>
              <div class="Text_38 IUText IUBox">
                <p><strong>품질이 좋습니다</strong></p>  
              </div>
              <div class="Text_39 IUText IUBox">
                <p><strong>합리적입니다</strong></p>  
              </div>
              <div class="Text_40 IUText IUBox">
                <p><strong>밤 12시까지</strong></p>  
              </div>
              <div class="Text_43 IUText IUBox">
                <p>스마트폰 어플리케이션을</p>
              <p>통해&nbsp;편리하게 주문하세요</p>  
              </div>
              <div class="Text_44 IUText IUBox">
                <p>서울에서 가장 잘 하는</p>
              <p>세탁 파트너들과 함께 합니다</p>  
              </div>
              <div class="Text_45 IUText IUBox">
                <p>와이셔츠 2,000원,</p>
              <p>정장 6,000원의 합리적인 가격</p>  
              </div>
              <div class="Text_46 IUText IUBox">
                <p>아침 10시부터 밤 12시까지</p>
              <p>언제든지 달려갑니다</p>  
              </div>
            </div>
            <div class="Text_47 IUText IUBox">
              <p>HOW IT WORKS</p>  
            </div>
          </div>
        </div>
        <div id="Section_81" class="Section_81 IUSection IUBox">
          <div class="CenterBox_81 IUCenterBox IUBox">
            <div class="Box_48 IUBox">
              <div class="Text_53 IUText IUBox ">
                <p>INCHEON</p>  
              </div>
              <div class="Text_54 IUText IUBox">
                <p><strong>인천광역시</strong></p>
              <p>&nbsp;</p>
              <p>남동구, 남구, 동구, 중구, 연수구</p>  
              </div>
              <div class="Box_79 IUBox">
              </div>
            </div>
            <div class="Box_50 IUBox">
              <div class="Text_48 IUText IUBox ">
                <p>SEOUL</p>  
              </div>
              <div class="Text_50 IUText IUBox">
                <p><strong>서울특별시</strong></p>
              <p>&nbsp;</p>
              <p>강남구, 서초구, 마포구, 용산구, 동작구, 관악구, 성동구,</p>
              <p>영등포구(여의도동, 당산동), 서대문구(신촌동, 연희동, 창천동)</p>  
              </div>
              <img class="S_Image_52 IUBox" src="./resources/css/pages/project/img_map1.png">
            </div>
          </div>
        </div>
        <div id="Section_27" class="Section_27 IUSection IUBox">
          <div class="CenterBox IUCenterBox IUBox">
            <div class="Text_56 IUText IUBox">
              <p>PRICE</p>  
            </div>
            <div class="Box_57 IUBox">
              <img class="S_Image_55 IUBox" src="./resources/css/pages/project/ic_item_y_shirt_select.png">
              <img class="S_Image_58 IUBox" src="./resources/css/pages/project/ic_item_suit_select.png">
              <img class="S_Image_59 IUBox" src="./resources/css/pages/project/ic_item_shoes_select.png">
              <img class="S_Image_60 IUBox" src="./resources/css/pages/project/ic_item_one_piece_select.png">
              <div class="Text_61 IUText IUBox">
                <p><strong>와이셔츠</strong></p>
              <p>2,000원</p>  
              </div>
              <div class="Text_62 IUText IUBox">
                <p><strong>정장</strong></p>
              <p>6,000원</p>  
              </div>
              <div class="Text_63 IUText IUBox">
                <p><strong>원피스</strong></p>
              <p>7,000원</p>  
              </div>
              <div class="Text_64 IUText IUBox">
                <p><strong>신발</strong></p>
              <p>5,000원</p>  
              </div>
            </div>
            <div class="Text_65 IUText IUBox iuPopUpButton IUBoxWithHover" popupButtonTargetId="PopUp">
              <p>전체 가격 보기</p>  
            </div>
            <div class="Box_68 IUBox">
            </div>
          </div>
        </div>
      </div>
      <div class="Footer IUFooter IUBox">
        <div class="CenterBox_14 IUCenterBox IUBox">
          <div class="Text_15 IUText IUBox">
            <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0><strong>고객센터</strong>&nbsp;070-7552-1385</p>
          <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0><strong>E-mail</strong>&nbsp;help@cleanbasket.co.kr</p>
          <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>(주)워시앱코리아 <strong>대표</strong>&nbsp;김우진 &nbsp;| &nbsp;<strong>사업자번호</strong>&nbsp;220-88-86968</p>
          <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0><strong>주소</strong>&nbsp;서울 강남구 봉은사로16길 16 타비쉬빌딩 1층</p>
          <p class='IUViewPortChangeableText' maxViewPort=767 minViewPort=0>Copyright &copy; Wash App Korea.&nbsp;All rights reserved.</p>  
            <p class='IUViewPortChangeableText' maxViewPort=9999 minViewPort=768><strong>고객센터</strong>&nbsp;070-7552-1385 &nbsp;|&nbsp;&nbsp;<strong>E-mail</strong>&nbsp;help@cleanbasket.co.kr</p>
          <p class='IUViewPortChangeableText' maxViewPort=9999 minViewPort=768>(주)워시앱코리아 <strong>대표</strong>&nbsp;김우진 &nbsp;| &nbsp;<strong>사업자번호</strong>&nbsp;220-88-86968</p>
          <p class='IUViewPortChangeableText' maxViewPort=9999 minViewPort=768><strong>주소</strong>&nbsp;서울 강남구 봉은사로16길 16 타비쉬빌딩 1층</p>
          <p class='IUViewPortChangeableText' maxViewPort=9999 minViewPort=768>Copyright &copy; Wash App Korea.&nbsp;All rights reserved.</p>  
          </div>
          <div class="FBLike IUBox">
          <iframe src="//www.facebook.com/plugins/like.php?href=https://www.facebook.com/cleanbasket/+&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;colorscheme=light&amp;" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px" allowTransparency="true"></iframe>
          </div>
        </div>
      </div>
    </div>
      <div id="PopUp" class="PopUp IUPopUp IUBox IUHCenter" PopUpShowDuration="0.4" PopUpShowAnimation="topdown" externalClose="true">
        <div class="TabView IUTabView IUBox" JQueryShowAnimation="transition.slideDownIn">
          <div class="TabHeader IUTabHeader IUBox">
            <div class="TabHeaderItem IUTabHeaderItem IUBox">
              <div class="TabHeaderDefaultItem IUTabHeaderDefaultItem IUBox">
                <div class="Cell IUText IUBox">
                  <p>비즈니스</p>  
                </div>
              </div>
              <div class="TabHeaderActiveItem IUTabHeaderActiveItem IUBox">
                <div class="Cell_109 IUText IUBox">
                  <p>비즈니스</p>  
                </div>
              </div>
            </div>
            <div class="TabHeaderItem_109 IUTabHeaderItem IUBox">
              <div class="TabHeaderDefaultItem_109 IUTabHeaderDefaultItem IUBox">
                <div class="Cell_110 IUText IUBox">
                  <p>상의/하의</p>  
                </div>
              </div>
              <div class="TabHeaderActiveItem_109 IUTabHeaderActiveItem IUBox">
                <div class="Cell_111 IUText IUBox">
                  <p>상의/하의</p>
                <p>&nbsp;</p>  
                </div>
              </div>
            </div>
            <div class="TabHeaderItem_114 IUTabHeaderItem IUBox">
              <div class="TabHeaderDefaultItem_114 IUTabHeaderDefaultItem IUBox">
                <div class="Cell_114 IUText IUBox">
                  <p>아우터</p>  
                </div>
              </div>
              <div class="TabHeaderActiveItem_114 IUTabHeaderActiveItem IUBox">
                <div class="Cell_115 IUText IUBox">
                  <p>아우터</p>  
                </div>
              </div>
            </div>
            <div class="TabHeaderItem_121 IUTabHeaderItem IUBox">
              <div class="TabHeaderDefaultItem_121 IUTabHeaderDefaultItem IUBox">
                <div class="Cell_121 IUText IUBox">
                  <p>기타/이불</p>  
                </div>
              </div>
              <div class="TabHeaderActiveItem_121 IUTabHeaderActiveItem IUBox">
                <div class="Cell_122 IUText IUBox">
                  <p>기타/이불</p>  
                </div>
              </div>
            </div>
            <div class="TabHeaderItem_128 IUTabHeaderItem IUBox">
              <div class="TabHeaderDefaultItem_128 IUTabHeaderDefaultItem IUBox">
                <div class="Cell_128 IUText IUBox">
                  <p>신발/가방</p>  
                </div>
              </div>
              <div class="TabHeaderActiveItem_128 IUTabHeaderActiveItem IUBox">
                <div class="Cell_129 IUText IUBox">
                  <p>신발/가방</p>  
                </div>
              </div>
            </div>
          </div>
          <div class="TabContent IUTabContent IUBox">
            <div class="TabContentItem IUTabContentItem IUBox">
              <div class="Cell_130 IUText IUBox">
                <p>와이셔츠 <strong>2,000원</strong></p>  
              </div>
              <div class="Cell_131 IUText IUBox">
                <p>정장 한 벌 <strong>6,000원</strong></p>  
              </div>
              <div class="Cell_132 IUText IUBox">
                <p>정장 상의 <strong>3,500원</strong></p>  
              </div>
              <div class="Cell_133 IUText IUBox">
                <p>정장 하의&nbsp;<strong>3,500원</strong></p>  
              </div>
              <div class="Cell_134 IUText IUBox">
                <p>여성 정장 상의 <strong>3,500원</strong></p>  
              </div>
              <div class="Cell_135 IUText IUBox">
                <p>여성 정장 하의&nbsp;<strong>3,500원</strong></p>  
              </div>
            </div>
            <div class="TabContentItem_109 IUTabContentItem IUBox">
              <div class="Cell_147 IUText IUBox">
                <p>바지&nbsp;<strong>3,000원</strong></p>  
              </div>
              <div class="Cell_148 IUText IUBox">
                <p>스커트 <strong>3,000원</strong></p>  
              </div>
              <div class="Cell_140 IUText IUBox">
                <p>블라우스&nbsp;<strong>4,000원 ~</strong></p>  
              </div>
              <div class="Cell_141 IUText IUBox">
                <p>롱스웨터 <strong>5,000원</strong></p>  
              </div>
              <div class="Cell_142 IUText IUBox">
                <p>스웨터&nbsp;<strong>4,000원</strong></p>  
              </div>
              <div class="Cell_143 IUText IUBox">
                <p>가디건&nbsp;<strong>4,000원</strong></p>  
              </div>
              <div class="Cell_144 IUText IUBox">
                <p>티셔츠&nbsp;<strong>3,000원</strong></p>  
              </div>
              <div class="Cell_145 IUText IUBox">
                <p>조끼 <strong>4,000원</strong></p>  
              </div>
            </div>
            <div class="TabContentItem_116 IUTabContentItem IUBox">
              <div class="Cell_151 IUText IUBox">
                <p>코트&nbsp;<strong>8,000원 ~</strong></p>  
              </div>
              <div class="Cell_152 IUText IUBox">
                <p>롱코트&nbsp;<strong>10,000원</strong></p>  
              </div>
              <div class="Cell_153 IUText IUBox">
                <p>트렌치 코트&nbsp;<strong>12,000원</strong></p>  
              </div>
              <div class="Cell_154 IUText IUBox">
                <p>점퍼 <strong>7,000 ~</strong></p>  
              </div>
              <div class="Cell_155 IUText IUBox">
                <p>가죽점퍼(S) <strong>30,000원 ~</strong></p>  
              </div>
              <div class="Cell_156 IUText IUBox">
                <p>가죽점퍼(L)&nbsp;<strong>40,000원 ~</strong></p>  
              </div>
              <div class="Cell_158 IUText IUBox">
                <p>패딩/아웃도어&nbsp;<strong>12,000원</strong></p>  
              </div>
              <div class="Cell_159 IUText IUBox">
                <p>골프웨어&nbsp;<strong>10,000원</strong></p>  
              </div>
              <div class="Cell_161 IUText IUBox">
                <p>자켓&nbsp;<strong>4,000원 ~</strong></p>  
              </div>
            </div>
            <div class="TabContentItem_123 IUTabContentItem IUBox">
              <div class="Cell_164 IUText IUBox">
                <p>원피스&nbsp;<strong>7,000원 ~</strong></p>  
              </div>
              <div class="Cell_165 IUText IUBox">
                <p>교복&nbsp;<strong>5,000원</strong></p>  
              </div>
              <div class="Cell_166 IUText IUBox">
                <p>한복&nbsp;<strong>15,000원</strong></p>  
              </div>
              <div class="Cell_167 IUText IUBox">
                <p>넥타이&nbsp;<strong>1,000원</strong></p>  
              </div>
              <div class="Cell_168 IUText IUBox">
                <p>스키복 상의&nbsp;<strong>15,000원</strong></p>  
              </div>
              <div class="Cell_169 IUText IUBox">
                <p>스키복 하의 <strong>15,000원</strong></p>  
              </div>
              <div class="Cell_171 IUText IUBox">
                <p>이불(S/D/Q)&nbsp;<span style="font-size: 8pt;"><strong>10,000/15,000/18,000원</strong></span></p>  
              </div>
              <div class="Cell_172 IUText IUBox">
                <p><span style="font-size: 8pt;">오리털 이불(S/D/Q)&nbsp;</span><span style="font-size: 8pt;"><strong>21,000/24,000/30,000원</strong></span></p>  
              </div>
              <div class="Cell_173 IUText IUBox">
                <p><span style="font-size: 8pt;">거위털 이불(S/D/Q) <strong>23,000/28,000/35,000원</strong></span></p>  
              </div>
              <div class="Cell_174 IUText IUBox">
                <p>스카프/목도리 <strong>2,000원</strong></p>  
              </div>
            </div>
            <div class="TabContentItem_130 IUTabContentItem IUBox">
              <div class="Cell_175 IUText IUBox">
                <p>운동화&nbsp;<strong>5,000원 ~</strong></p>  
              </div>
              <div class="Cell_176 IUText IUBox">
                <p>등산화&nbsp;<strong>7,000원</strong></p>  
              </div>
              <div class="Cell_177 IUText IUBox">
                <p>구두&nbsp;<strong>7,000원</strong></p>  
              </div>
              <div class="Cell_178 IUText IUBox">
                <p>어그 부츠&nbsp;<strong>15,000</strong></p>  
              </div>
              <div class="Cell_179 IUText IUBox">
                <p>책가방&nbsp;<strong>8,000원 ~</strong></p>  
              </div>
              <div class="Cell_180 IUText IUBox">
                <p>명품 가방(천)&nbsp;<strong>50,000원</strong></p>  
              </div>
              <div class="Cell_182 IUText IUBox">
                <p>명품 가방(가죽)&nbsp;<strong>70,000원</strong></p>  
              </div>
              <div class="Cell_183 IUText IUBox">
                <p>가방(천) <strong>40,000원</strong></p>  
              </div>
              <div class="Cell_184 IUText IUBox">
                <p>골프화&nbsp;<strong>8,000원 ~</strong></p>  
              </div>
              <div class="Cell_185 IUText IUBox">
                <p>가방(가죽) <strong>50,000원</strong></p>  
              </div>
            </div>
          </div>
        </div>
        <div class="IUPopUp-closeButton"></div>  
      </div>
      <div id="IUPopUpDimColor" class="IUPopUpDimColor" style="display:none;"></div>  
  </body>  
</HTML>

